# Generated by Django 5.0.6 on 2026-05-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_agent_aadhar_card_image_agent_aadhar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
