# Generated by Django 5.0.6 on 2026-05-15 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_agent_aadhar_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('aadhaar_card', models.FileField(upload_to='customers/aadhaar/')),
                ('pan_card', models.FileField(upload_to='customers/pan/')),
                ('electricity_bill', models.FileField(upload_to='customers/bills/')),
                ('bank_document', models.FileField(upload_to='customers/bank/')),
                ('roof_photo', models.FileField(upload_to='customers/roof/')),
                ('meter_photo', models.FileField(upload_to='customers/meter/')),
                ('passport_photo', models.FileField(upload_to='customers/photos/')),
                ('ownership_proof', models.FileField(upload_to='customers/ownership/')),
                ('vendor_quotation', models.FileField(upload_to='customers/quotations/')),
                ('mobile_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='app.agent')),
            ],
        ),
    ]
