# Generated by Django 5.0.6 on 2026-05-15 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('UPI', 'UPI'), ('Cash', 'Cash')], max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.agent')),
            ],
        ),
    ]
