# Generated by Django 5.0.6 on 2026-05-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='utr_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
