# Generated by Django 5.0.6 on 2026-05-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_payment_utr_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('Regular', 'Regular Commission'), ('Extra', 'Extra Commission')], default='Regular', max_length=20),
        ),
    ]
