# Generated by Django 5.0.6 on 2026-05-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
