# Generated by Django 5.0.6 on 2026-05-19 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_vendor_vendor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='assigned_to_vendor_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to='app.vendor'),
        ),
        migrations.AddField(
            model_name='customer',
            name='vendor_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
