# Generated by Django 5.0.6 on 2026-05-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_customer_assigned_to_vendor_at_customer_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vendor_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('Complete', 'Complete'), ('Hold', 'Hold')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='vendor_status_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='vendor_status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
