# Generated by Django 5.0.6 on 2026-05-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_vendor_last_seen_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='extra_payment_done',
            field=models.BooleanField(default=False),
        ),
    ]
