# Generated by Django 5.0.6 on 2026-05-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_customer_extra_payment_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='extra_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
