# Generated by Django 5.0.6 on 2026-05-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_customer_extra_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='commission_per_customer',
            field=models.DecimalField(blank=True, decimal_places=2, default=20.0, max_digits=10, null=True),
        ),
    ]
