# Generated by Django 5.0.6 on 2026-05-27 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_agent_commission_per_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vendor_doc_payment_done',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='VendorDocumentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('method', models.CharField(choices=[('UPI', 'UPI'), ('Cash', 'Cash')], max_length=10)),
                ('utr_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_doc_payments', to='app.customer')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_payments', to='app.vendor')),
            ],
        ),
    ]
