# Generated by Django 5.0.6 on 2026-05-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_customer_vendor_doc_payment_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status_updated_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='status_updated_by_role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
