# Generated by Django 5.0.6 on 2026-05-28 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_customer_status_updated_by_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('changed_by_name', models.CharField(max_length=255)),
                ('changed_by_role', models.CharField(max_length=20)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='app.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
