# Generated by Django 5.0.6 on 2026-05-30 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_customerstatushistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('Admin', 'Admin'), ('Agent', 'Agent')], max_length=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='agent_chat_images/')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='app.agent')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
