# Generated by Django 5.0.6 on 2026-05-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_agentchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
